# Github Repository Actions 페이지에 나타낼 이름
name: Deploy costarica-api

# event trigger
on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - develop

permissions:
  contents: read

# jobs의 속성 아래 hash table 형태로 작업내용을 정의 (hash table의 키 값은 적절한 key 값으로 설정)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ## GitHub-Actionsjdk setting
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash

#    - name: Test with Gradle # test application build
#      run: ./gradlew test
